apiVersion: v1
kind: Service
metadata:
  name: cb-haproxy-service
  namespace: {{ default "clearblade" .Values.global.namespace }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{.Values.primaryIP}}
  ports:
    - name: http
      targetPort: 8080
      port: {{ .Values.ports.http }}
      protocol: TCP
    - name: https
      targetPort: 8443
      port: {{ .Values.ports.https }}
      protocol: TCP
    - name: prometheus
      targetPort: 9090
      port: 9090
      protocol: TCP
    - name: prometheus-managed
      targetPort: 9000
      port: 9000
      protocol: TCP
    - name: grafana
      targetPort: 3000
      port: 3000
      protocol: TCP   
    - name: exporter
      targetPort: 9876
      port: 9876
      protocol: TCP
  selector:
    app: cb-haproxy
---
apiVersion: v1
kind: Service
metadata: 
  name: cb-haproxy-monitoring-service
  namespace: {{ $default "clearblade" .Values.global.namespace }}
  labels:
    app: cb-haproxy
spec:
  ports:
  - name: metrics
    port: 9101
    protocol: TCP
  selector:
    app: cb-haproxy