replicas: 3
monitoringEnabled: false
image: timescale/timescaledb
imageTag: "latest-pg15"
requestCPU: 1
requestMemory: 4G
limitCPU: 1
limitMemory: 4G
user:
  primary: cbuser
  replica: cbreplication
port: 5432

livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 6
readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

storageSize: 100Gi
postgres0DiskName: postgres-0
postgres1DiskName: postgres-1
postgres2DiskName: postgres-2
volumeAZ:
volumeHandle: