apiVersion: v2
name: clearblade-monitoring
description: ClearBlade IoT Enterprise monitoring
type: application
version: 2.13.5

dependencies:
  - name: cb-monitoring
    version: 2.13.5
    condition: cb-monitoring.enabled
    repository: file://charts/cb-monitoring
  - name: cb-haproxy
    version: 2.13.5
    condition: cb-haproxy.enabled
    repository: file://charts/cb-haproxy
