#!/bin/bash
set -e

echo "Initializing Database for ClearBlade Platform"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $PRIMARY_USER;
    ALTER USER $PRIMARY_USER WITH SUPERUSER;
    ALTER USER $PRIMARY_USER WITH PASSWORD '$PRIMARY_PASSWORD';
    CREATE USER $REPLICA_USER REPLICATION LOGIN ENCRYPTED PASSWORD '$REPLICA_PASSWORD';
    CREATE DATABASE admin;
    GRANT ALL PRIVILEGES ON DATABASE admin TO $PRIMARY_USER;
    CREATE EXTENSION pg_stat_statements;
    CREATE EXTENSION IF NOT EXISTS timescaledb;
    CREATE DATABASE secondary;
    GRANT ALL PRIVILEGES ON DATABASE secondary TO $PRIMARY_USER;
EOSQL