global:
  namespace: monitoring # Namespace to be created for the monitoring resources (one per cluster, must be unique per deployment if non-wildcard TLS certificates are used)
  deploymentnamespace: REPLACE # the existing namespace that clearblade is deployed in. Not necessary for GMP
  nodeSelector: REPLACE # Optional nodeSelector. Leave blank if not utilizing.
  tolerations: # Optional taint tolerations. Add as many key blocks as necessary. Leave blank if not utilizing.
    # - key: "key1"
    #   operator: "Equal"
    #   value: "value1"
    #   effect: "NoSchedule"
  gcp:
    project: REPLACE
    region: REPLACE
    gsmReadServiceAccount: clearblade-gsm-read # GCP Service account to be used in helm install command. Needs secret access and workload identity
  advanced:
    predefinedNamespace: false # Set to true if you manage the namespace outside of helm.
    secrets:
      manager: gsm
  GMP: false # Change to true to use Google Managed Prometheus, leave false for standalone Prometheus deployment (standard)

cb-haproxy:
  image: haproxy
  imageTag: 2.6-alpine
  grafanaEnabled: true # Bundled Grafana
  ip:
    primary: REPLACE # static external IP in DNS record
  prometheus:
    user: REPLACE # Prometheus frontend username
    sha256password: REPLACE # Generated with: mkpasswd -m sha-256 mypassword123. See: https://www.haproxy.com/documentation/haproxy-configuration-tutorials/authentication/basic-authentication/
  resourceRequests:
    cpu: 1
    memory: 4G
  resourceLimits:
    cpu: 1
    memory: 4G

cb-monitoring:
  monitoringURL: REPLACE
  grafana:
    enabled: true # Bundled Grafana
    clusterName: REPLACE # Used to filter dashboard queries to this cluster only. 
    adminUsername: REPLACE # Grafana frontend login
    base64password: REPLACE # Base64 Encoded password of your choice
  resourceRequests:
    cpu: 1
    memory: 4G
  resourceLimits:
    cpu: 1
    memory: 4G
  clearbladereplicas: 1 # Number of ClearBlade pods in deployment. Used for prometheus scrape config. Not necessary for GMP
  haproxyreplicas: 1 # Number of HAProxy pods in deployment. Used for prometheus scrape config. Not necessary for GMP
  postgresreplicas: 1 # Number of Postgres pods in deployment. Used for prometheus scrape config. not necessary for GMP
  prometheusDisk: REPLACE #OPTIONAL disk for prometheus data. Leave blank if not using. Not necessary for GMP deployments
  prometheusDiskSize: REPLACE #OPTIONAL size of disk above, include unit. example: 200G