apiVersion: v1
kind: Service
metadata:
  name: cb-redis-service
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - port: 6379
      protocol: TCP
      name: redis
    {{- if .Values.monitoringEnabled }}
    - port: 9121
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    app: cb-redis