{{ if and (ne .Values.global.secretManager "gsm") (ne .Values.global.secretManager "asm")}}
apiVersion: v1
kind: Secret
metadata:
  name: clearblade-secrets
  namespace: {{ default "clearblade" .Values.global.namespace }}
data:
  postgresPassword: {{ .Values.global.postgresPassword | b64enc }}
  mekfile: {{ .Values.global.mekfile | b64enc }}
{{- end }}
