{{- if .Values.global.imagePullerSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: gcr-json-key
  namespace: {{ .Values.global.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.global.imagePullerSecret }}
{{- end }}
