{{- if eq .Values.global.cloud "gcp" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clearblade-gsm-read
  namespace: {{ default "clearblade" .Values.global.namespace }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.global.gcpGSMServiceAccount }}@{{ .Values.global.gcpProject }}.iam.gserviceaccount.com
{{- end}}