apiVersion: apps/v1
kind: Deployment
metadata:
  name: cb-ia
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: cb-ia
  replicas: 1
  template:
    metadata:
      labels:
        app: cb-ia
        app.kubernetes.io/name: managed-prom
    spec:
      {{- if .Values.global.imagePullerSecret }}
      imagePullSecrets:
        - name: gcr-json-key
      {{- end }}
      {{- if .Values.checkClearbladeReadiness }}
      initContainers:
      - name: check-clearblade-readiness
        image: ellerbrock/alpine-bash-curl-ssl
        command:
        - bash
        - "-c"
        - |
          set -x;
          while [ $(curl -sw '%{http_code}' "https://{{ .Values.global.enterprise.baseURL }}/api/about" -o /dev/null) -ne 200 ]; do
            echo waiting for clearblade; sleep 5;
          done;
          # Give clearblade just a little more time to really start for real
          sleep 10;
      {{- end }}
      containers:
        - name: cb-ia
          image: gcr.io/api-project-320446546234/ia:{{ .Values.global.IA.version}}
          command:  ["ia-sidecar"]
          args: ["-reg-key={{ .Values.global.enterprise.registrationKey }}", "-url=https://{{ .Values.global.enterprise.baseURL }}", "-message-url=https://{{ .Values.global.enterprise.baseURL }}", "-instance-id={{ .Values.global.enterprise.instanceID }}"]
          volumeMounts:
          - name: ia
            mountPath: /etc/clearblade/conf/ia
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          resources:
            limits:
              cpu: {{ .Values.resourceLimits.cpu }}
              memory: {{ .Values.resourceLimits.memory }}
      {{- if .Values.global.tolerations }}
      tolerations:
{{ .Values.global.tolerations | toYaml | indent 6 }}
      {{- end }}
      {{- if .Values.global.nodeSelector }}
      nodeSelector:
        {{ .Values.global.nodeSelector }}
      {{- end }}
      volumes:
        - name: ia
          persistentVolumeClaim:
            claimName: cb-ia-pvc