{{- if eq ((.Values.global.advanced.secrets).manager) "none" }}
apiVersion: v1
kind: Secret
metadata:
  name: clearblade-secrets
  namespace: {{ .Values.global.namespace }}
data:
  postgresPassword: {{ .Values.global.advanced.secrets.postgresPassword | b64enc }}
  mekfile: {{ .Values.global.advanced.secrets.mekfile | b64enc }}
{{- end }}
