apiVersion: v1
kind: Service
metadata:
  name: cb-iotcore-service
  namespace: {{ default "clearblade" .Values.global.namespace }}
spec:
  ports:
  - name: ui
    targetPort: 8080
    port: 3000
    protocol: TCP
  selector:
    app: cb-iotcore