apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cb-iotcore-pvc
  namespace: {{ default "clearblade" .Values.global.namespace }}
spec:
  storageClassName: {{ .Values.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageSize }}