apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ default "clearblade" .Values.global.namespace}}-iotcore-pv
  namespace: {{ default "clearblade" .Values.global.namespace}}
spec:
  storageClassName: {{ .Values.global.storageClassName }}
  capacity:
    storage: {{ .Values.storageSize }}
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: {{ default "clearblade" .Values.global.namespace }}
    name: cb-iotcore-pvc
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/{{ .Values.global.gcpProject }}/regions/{{ .Values.global.gcpRegion }}/disks/{{ default "clearblade" .Values.global.namespace }}-iotcore
    fsType: ext4