apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cb-iotcore-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  storageClassName: {{ .Values.storage.class }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}