apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.global.namespace}}-cb-iotcore-pv
  namespace: {{ .Values.global.namespace}}
spec:
  storageClassName: {{ .Values.storage.class }}
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: {{ .Values.global.namespace }}
    name: cb-iotcore-pvc
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/{{ .Values.global.gcp.project }}/regions/{{ .Values.global.gcp.region }}/disks/{{ .Values.global.namespace }}-{{ .Values.storage.gceDisk_iotcore }}
    fsType: ext4