enabled: true
grafana:
  enabled: true
  clusterName: # Used to filter dashboard queries to this cluster only. Leave blank and all clusters in the project area will show in the dashboard.
  datasource: "Prometheus"
  adminUsername: ""
  base64password: ""
alerts:
  slack:
    enabled: false
    url: ""
monitoringURL: ""
resourceRequests:
    cpu: 1
    memory: 4G
resourceLimits:
    cpu: 1
    memory: 4G
