apiVersion: apps/v1
kind: Deployment
metadata:
  name: cb-console
  namespace: {{ .Values.global.namespace }}
  labels:
    app: cb-console
spec:
  selector:
    matchLabels:
      app: cb-console
  replicas: 1
  template:
    metadata:
      labels:
        app: cb-console
        app.kubernetes.io/name: managed-prom
    spec:
      {{- if .Values.global.imagePullerSecret }}
      imagePullSecrets:
        - name: gcr-json-key
      {{- end }}
      {{- if .Values.iaMount }}
      volumes:
        - name: console
          persistentVolumeClaim:
            claimName: pvc-cb-console-cb-console-{{ .Values.global.namespace }}
      {{- end }}
      containers:
        - name: cb-console
          image: "gcr.io/api-project-320446546234/cb_console:{{ .Values.global.enterprise.version }}"
          command:  ["cb_console"]
          args: [
            {{- include "cb-console.platformURL" . | indent 12 }},
            {{- include "cb-console.wsMqttMessagingURL" . | indent 12 }},
            {{- include "cb-console.wsMqttMessagingPort" . | indent 12 }},
            "-checkCert=true"
          ]
          {{- if .Values.iaMount }}
          volumeMounts:
            - name: {{ .Values.storage.name }} 
              mountPath: /asset_monitor_files
          {{- end }}
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: {{ .Values.resourceRequests.memory }}
              cpu: {{ .Values.resourceRequests.cpu }}
            limits:
              cpu: {{ .Values.resourceLimits.cpu }}
              memory: {{ .Values.resourceLimits.memory }}
      {{- if .Values.global.tolerations }}
      tolerations:
{{ .Values.global.tolerations | toYaml | indent 6 }}
      {{- end }}
      {{- if .Values.global.nodeSelector }}
      nodeSelector:
        {{ .Values.global.nodeSelector }}
      {{- end }}