apiVersion: v1
kind: Service
metadata:
  name: cb-console-service
  namespace: {{ .Values.global.namespace }}
spec:
  {{- if ((.Values.global.advanced.externalHaproxy).loadBalancer) }}
  type: LoadBalancer
  ports:
    - name: console-http
      targetPort: 3000
      port: {{ .Values.global.advanced.externalHaproxy.ports.cbConsole.http }}
  {{- else}}
  ports:
    - name: console-http
      port: 3000
      protocol: TCP
  {{- end }}
  selector:
    app: cb-console