apiVersion: v1
kind: Service
metadata:
  name: cb-console-service
  namespace: {{ default "clearblade" .Values.global.namespace }}
spec:
  {{- if (.Values.global.externalHaproxyCbConsoleHttpPort) }}
  type: LoadBalancer
  ports:
    - name: console-http
      targetPort: 3000
      port: {{ .Values.global.externalHaproxyCbConsoleHttpPort }}
  {{- else }}
  ports:
    - name: console-http
      port: 3000
      protocol: TCP
  {{- end }}
  selector:
    app: cb-console