{{- if .Values.iaMount }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: console-{{ .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
spec:
  storageClassName: {{ .Values.storage.class }}
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: {{ .Values.global.namespace }}
    name: pvc-cb-console-cb-console-{{ .Values.global.namespace }}
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/{{ .Values.global.gcp.project }}/regions/{{ .Values.global.gcp.region }}/disks/{{ .Values.global.namespace }}-{{ .Values.storage.gceDisk_console }}
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.global.namespace }}
  name: pvc-cb-console-cb-console-{{ .Values.global.namespace }}
spec:
  storageClassName: {{ .Values.storage.class }}
  volumeName: console-{{ .Values.global.namespace }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
{{- end }}