{{- if and (ne .Values.global.secretManager "gsm") (ne .Values.global.secretManager "asm")}}
apiVersion: v1
kind: Secret
metadata:
  name: cb-haproxy-secrets
  namespace: {{ default "clearblade" .Values.global.namespace }}
data:
  cert.pem: {{ .Values.global.tlsCertificate | b64enc }}
{{- end }}
