apiVersion: v1
kind: Secret
metadata:
  name: cb-haproxy-config
  namespace: {{ default "clearblade" .Values.global.namespace }}
data:
  haproxy.cfg: |
{{ (tpl (.Files.Get "configs/haproxy.cfg") .) | b64enc | indent 4 }}