apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-{{ default "monitoring" .Values.global.namespace }}
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-{{ default "monitoring" .Values.global.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-{{ default "monitoring" .Values.global.namespace }}
subjects:
- kind: ServiceAccount
  {{- if eq (default .Values.global.gmpEnabled false) false}}
  name: default
  {{- else }}
  name: {{ .Values.global.gcpGSMServiceAccount }}
  {{- end }}
  namespace: {{ default "monitoring" .Values.global.namespace }}