{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: datasources
  namespace: {{ default "monitoring" .Values.global.namespace }}
{{- if eq (default .Values.global.gmpEnabled false) true }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: {{ .Values.grafana.datasource }}
      type: prometheus
      url: http://prometheus-managed.{{ default "monitoring" .Values.global.namespace }}:9090
      isDefault: true
      jsonData:
        manageAlerts: false
        timeout: 60
{{- else }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: {{ .Values.grafana.datasource }}
      type: prometheus
      url: http://prometheus-frontend.{{ default "monitoring" .Values.global.namespace }}.svc.cluster.local:9090
      isDefault: true
      jsonData:
        manageAlerts: false
        timeout: 60
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dashboards
  namespace: {{ default "monitoring" .Values.global.namespace }}
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
    - name: 'main'
      orgId: 1
      folder: 'main-dir'
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /etc/grafana/provisioning/template

{{- end }}