{{- if eq (default .Values.global.GMP false) false}}
{{- else }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-managed
  namespace: {{ default "monitoring" .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-managed
  template:
    metadata:
      labels:
        app: prometheus-managed
    spec:
      serviceAccountName: clearblade-gsm-read
      automountServiceAccountToken: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64
                - amd64
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      containers:
        - name: prometheus-managed
          image: gke.gcr.io/prometheus-engine/frontend:v0.7.0-gke.0
          args:
            - "--web.listen-address=:9090"
            - "--query.project-id={{ .Values.global.gcp.project }}"
          ports:
          - name: web
            containerPort: 9090
          readinessProbe:
            httpGet:
              path: /-/ready
              port: web
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - all
            privileged: false
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: web
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-managed
  namespace: {{ default "monitoring" .Values.global.namespace }}
spec:
  clusterIP: None
  selector:
    app: prometheus-managed
  ports:
    - name: web
      port: 9090
{{- end}}