{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: datasources
  namespace: {{ .Values.global.namespace }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: {{ .Values.grafana.datasource }}
      type: prometheus
      url: http://prometheus-managed.{{ .Values.global.namespace }}:9090
      isDefault: true
      jsonData:
        manageAlerts: false
        timeout: 60

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dashboards
  namespace: {{ .Values.global.namespace }}
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
    - name: 'main'
      orgId: 1
      folder: 'main-dir'
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /etc/grafana/provisioning/template

{{- end }}