{{- if eq .Values.replicas 1.0 }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cb-postgres-cb-postgres-0
  namespace: {{ .Values.global.namespace }}
spec:
  storageClassName: {{ .Values.storage.class }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
{{- end }}