{{- if eq ((.Values.global.advanced.secrets).manager) "none" }}
apiVersion: v1
kind: Secret
metadata:
  name: cb-postgres-secrets
  namespace: {{ .Values.global.namespace }}
data:
  primary-password: {{ .Values.global.advanced.secrets.postgresPassword | b64enc }}
  replica-password: {{ .Values.global.advanced.secrets.postgresPassword | b64enc }}
  postgres-password: {{ .Values.global.advanced.secrets.postgresPassword | b64enc }}
{{- end }}
