{{- if and (ne .Values.global.secretManager "gsm") (ne .Values.global.secretManager "asm")}}
apiVersion: v1
kind: Secret
metadata:
  name: cb-postgres-secrets
  namespace: {{ default "clearblade" .Values.global.namespace }}
data:
  primary-password: {{ .Values.global.postgresPassword | b64enc }}
  replica-password: {{ .Values.global.postgresPassword | b64enc }}
  postgres-password: {{ .Values.global.postgresPassword | b64enc }}
{{- end }}
