apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: {{ default "clearblade" .Values.global.namespace }}
  labels:    
{{ include "cb-postgres.labels" . | indent 4 }}
data:
{{ (tpl (.Files.Glob "configs/pg_hba.conf").AsConfig .) | indent 2 }}
{{ (tpl (.Files.Glob "configs/postgresql.conf").AsConfig .) | indent 2 }}