{{- if eq .Values.global.cloud "aws" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.global.namespace}}-postgres-0
  namespace: {{ .Values.global.namespace }}
spec:
  storageClassName: gp2
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: {{ .Values.global.namespace }}
    name: pvc-cb-postgres-cb-postgres-0
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: {{ .Values.global.eks.ebs.postgresVolumeHandle }}
{{- end }}
