{{- if eq .Values.replicas 1.0 }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cb-postgres-cb-postgres-0
  namespace: {{ default "clearblade" .Values.global.namespace }}
spec:
  storageClassName: {{ .Values.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageSize }}
{{- end }}