apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.global.namespace}}-postgres-0
  namespace: {{ .Values.global.namespace }}
spec:
  storageClassName: {{ .Values.storage.class }}
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: {{ .Values.global.namespace }}
    name: pvc-cb-postgres-cb-postgres-0
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/{{ .Values.global.gcp.project }}/regions/{{ .Values.global.gcp.region }}/disks/{{ .Values.global.namespace }}-{{ .Values.storage.gceDisk_postgres0 }}
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.global.namespace}}-postgres-1
  namespace: {{ .Values.global.namespace }}
spec:
  storageClassName: {{ .Values.storage.class }}
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: {{ .Values.global.namespace }}
    name: pvc-cb-postgres-cb-postgres-1
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/{{ .Values.global.gcp.project }}/regions/{{ .Values.global.gcp.region }}/disks/{{ .Values.global.namespace }}-{{ .Values.storage.gceDisk_postgres1 }}
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.global.namespace}}-postgres-2
  namespace: {{ .Values.global.namespace }}
spec:
  storageClassName: {{ .Values.storage.class }}
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: {{ .Values.global.namespace }}
    name: pvc-cb-postgres-cb-postgres-2
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/{{ .Values.global.gcp.project }}/regions/{{ .Values.global.gcp.region }}/disks/{{ .Values.global.namespace }}-{{ .Values.storage.gceDisk_postgres2 }}
    fsType: ext4
