{{- range $i, $e := until (.Values.replicas | int)}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cb-postgres-cb-postgres-{{i}}
  namespace: {{ default "clearblade" .Values.global.namespace }}
spec:
  storageClassName: {{ .Values.global.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageSize }}
{{- end }}